### ISSUE TITLE
Issue with Hadamard response in hr_server.py

### ISSUE THREAD

**Issue by oemertekin** [Samuel-Maddock/pure-LDP#4]
Hi @Samuel-Maddock ,

I seem to experiencing some issues when trying to run the code in 'Usage'. It throws an error originating from hr_server.py in the pure-LDP/pure_ldp/frequency_oracles/hadamard_response/ saying that the function k2k_hadamard couldn't be found. Looking at the import, it doesn't seem like it could find it because I don't see an internal folder in hadamard_response/ either.

Here is the import that is causing the error: from pure_ldp.frequency_oracles.hadamard_response.internal import k2k_hadamard

Best,
Ömer

**Comment by Samuel-Maddock** [comment]
Thanks for this! Seems like when building the package, it didn't include the internal module. I will work on a fix for this and hopefully get it out by the end of today.

In the meantime, you could clone this repo and use the package locally since the internal folder is there. You should clone from dev, since hadamard_response has a bug on master that I will also merge and push to PyPi at the end of the day.

Let me know if you run into anymore issues.

**Comment by Samuel-Maddock** [comment]
@oemertekin should hopefully have been fixed in 1.0.6, let me know if it hasn't

**Comment by oemertekin** [comment]
@Samuel-Maddock works like a charm! Thanks for the fix!
